### ISSUE TITLE
how to configure the enviroment?

### ISSUE THREAD

**Issue by codejeremy** [stalary/microservice-recruit#5]
hello:
       this  ids my first time that contact the type of this project and I just download the project,but don't know how to config? I hope that i can get your help,or con you give me points?thank you very much!

**Comment by stalary** [comment]
Config in https://github.com/stalary/pf-config


| |
stalary
|
|
stalary@163.com
|
签名由网易邮箱大师定制


On 10/23/2020 18:30，codejeremy<notifications@github.com> wrote：

hello:
this ids my first time that contact the type of this project and I just download the project,but don't know how to config? I hope that i can get your help,or con you give me points?thank you very much!

**Comment by codejeremy** [comment]
> Config in https://github.com/stalary/pf-config | | stalary | | stalary@163.com | 签名由网易邮箱大师定制 On 10/23/2020 18:30，codejeremy<notifications@github.com> wrote： hello: this ids my first time that contact the type of this project and I just download the project,but don't know how to config? I hope that i can get your help,or con you give me points?thank you very much! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for your reply! i have config the nocas,but the project still doesn't work, when i run the userApplication,the error occured, and i don't know how to do next,thanks again!

error:
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-10-23 03:42:57.087 ERROR [pf-user,,,] 4713 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
